name: Build web application

on: push
concurrency: ci_pipeline

jobs:
  test-build-deploy-project:
    name: Webapp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint
        env:
          NODE_ENV: test

      - name: Run unit tests
        run: npm run unit:test
        env:
          NODE_ENV: test
#      - name: Run integration tests
#        run: npm run integration:test
#        env:
#          NODE_ENV: test

#      - name: Deploying to QA
#        if: github.ref == 'refs/heads/main'
#        run: ./.github/workflows/deploy-to-qa.sh
#        env:
#          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
#          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
#
#      - name: Deploying to production
#        if: startsWith(github.ref, 'refs/heads/release/')
#        run: ./.github/workflows/deploy-to-production.sh
#        env:
#          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
#          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
